#!/bin/bash
echo "/*=========================================================================================="
echo "* [Record gif iamge on ubuntu.]"
echo "* Please install software when first use this tool."
echo "* sudo apt-get install xdotool byzanz"
echo "* position: look at xwininfo to check position of window."
echo "* xdotool getmouselocation will print position of mouse when click enter."
echo "* ORIGIN COMMAND: byzanz-record -d 10 -x 2712 -y 287 -w 500 -h 530 --delay=1 -v test.gif"
echo "* USAGE: ./record_gif name.gif 20"
echo "===========================================================================================*/"

wsleep=2

echo -n "Move mouse at left-top: "
sleep $wsleep
xx=$(xdotool getmouselocation)
IFS=" " 
arr=($xx)
s_x="${arr[0]:2}"
s_y="${arr[1]:2}"
echo "= ("$s_x", "$s_y")"

echo -n "Move mouse at right-bottom: "
sleep $wsleep
yy=$(xdotool getmouselocation)
IFS=" " 
arr=($yy)
e_x="${arr[0]:2}"
e_y="${arr[1]:2}"
echo "= ("$e_x", "$e_y")"

sleep $wsleep
w=$(($e_x-$s_x))
h=$(($e_y-$s_y))
cmd="byzanz-record -d $2 -x $s_x -y $s_y -w $w -h $h --delay=1 -v $1"

# echo $cmd

${cmd}&
sleep 1
for(( i=$2; i>0; i--)); do
{
    echo -n "$i";
    echo -ne "\b\b\b\b"
    sleep 1;
}
done

eog $1
